#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Scout — one-shot local setup
#
# Usage: bash setup.sh
#
# What it does:
#   1. Checks prerequisites (Docker, Ollama, Node, Python)
#   2. Creates .env with auto-generated secrets (skips if .env already exists)
#   3. Creates frontend/.env.local
#   4. Starts Docker infrastructure (docker compose up -d)
#   5. Creates the Python venv and installs backend dependencies
#   6. Prints next steps
# ─────────────────────────────────────────────────────────────────────────────
set -e
cd "$(dirname "$0")"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
ok()   { echo -e "${GREEN}✓${NC} $*"; }
warn() { echo -e "${YELLOW}!${NC} $*"; }
fail() { echo -e "${RED}✗${NC} $*"; exit 1; }

echo ""
echo "═══════════════════════════════════════"
echo "  Scout — Setup"
echo "═══════════════════════════════════════"
echo ""

# ── 1. Prerequisites ──────────────────────────────────────────────────────────
command -v docker   >/dev/null 2>&1 || fail "Docker not found. Install: https://docs.docker.com/get-docker/"
command -v node     >/dev/null 2>&1 || fail "Node.js not found. Install: https://nodejs.org/"
command -v python3  >/dev/null 2>&1 || fail "Python 3 not found. Install: https://python.org/"
command -v ollama   >/dev/null 2>&1 || warn "Ollama not found — install from https://ollama.com/ then run: ollama pull qwen2.5:14b && ollama pull nomic-embed-text"
ok "Prerequisites checked"

# ── 2. Generate .env ──────────────────────────────────────────────────────────
if [ -f .env ]; then
    warn ".env already exists — skipping generation (delete it to regenerate)"
else
    echo ""
    echo "Generating .env with secure secrets..."

    PG_PASS=$(openssl rand -hex 16)
    LF_DB_PASS=$(openssl rand -hex 16)
    LF_AUTH_SECRET=$(openssl rand -base64 32 | tr -d '\n')
    LF_SALT=$(openssl rand -hex 16)
    LF_ENC_KEY=$(openssl rand -hex 32)
    REDIS_PASS=$(openssl rand -hex 12)
    MINIO_PASS=$(openssl rand -hex 12)
    CH_PASS=$(openssl rand -hex 12)
    ADMIN_PASS=$(openssl rand -hex 10)

    cat > .env << EOF
# Auto-generated by setup.sh — edit API keys at the bottom if needed

# ── PostgreSQL ───────────────────────────────────────────────────────────────
POSTGRES_PASSWORD=${PG_PASS}
DATABASE_URL=postgresql://scout:${PG_PASS}@localhost:5432/scout

# ── Qdrant ───────────────────────────────────────────────────────────────────
QDRANT_HOST=localhost
QDRANT_PORT=6333

# ── Ollama ───────────────────────────────────────────────────────────────────
OLLAMA_BASE_URL=http://localhost:11434
LLM_MODEL=qwen2.5:14b
EMBEDDING_MODEL=nomic-embed-text

# ── Langfuse ─────────────────────────────────────────────────────────────────
LANGFUSE_HOST=http://localhost:3001
LANGFUSE_DB_PASSWORD=${LF_DB_PASS}
LANGFUSE_NEXTAUTH_SECRET=${LF_AUTH_SECRET}
LANGFUSE_SALT=${LF_SALT}
LANGFUSE_ENCRYPTION_KEY=${LF_ENC_KEY}
LANGFUSE_PUBLIC_KEY=pk-lf-change_me
LANGFUSE_SECRET_KEY=sk-lf-change_me

# Langfuse admin account — log in at http://localhost:3001
LANGFUSE_INIT_USER_EMAIL=admin@scout.local
LANGFUSE_INIT_USER_PASSWORD=${ADMIN_PASS}
LANGFUSE_INIT_USER_NAME=Admin

# ── Internal services ────────────────────────────────────────────────────────
REDIS_PASSWORD=${REDIS_PASS}
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=${MINIO_PASS}
CLICKHOUSE_PASSWORD=${CH_PASS}

# ── Data source API keys (optional — leave blank to skip) ────────────────────
OPENCORPORATES_API_KEY=
CRUNCHBASE_API_KEY=
EOF

    ok ".env created with auto-generated secrets"
    echo ""
    echo "   Langfuse admin login:"
    echo "   URL:      http://localhost:3001"
    echo "   Email:    admin@scout.local"
    echo "   Password: ${ADMIN_PASS}"
    echo ""
fi

# ── 3. frontend/.env.local ────────────────────────────────────────────────────
if [ ! -f frontend/.env.local ]; then
    cat > frontend/.env.local << 'EOF'
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_LANGFUSE_URL=http://localhost:3001
EOF
    ok "frontend/.env.local created"
else
    ok "frontend/.env.local already exists"
fi

# ── 4. Docker infrastructure ──────────────────────────────────────────────────
echo ""
echo "Starting Docker infrastructure..."
docker compose up -d
ok "Infrastructure started (PostgreSQL, Qdrant, Langfuse)"

# ── 5. Python venv + dependencies ─────────────────────────────────────────────
echo ""
echo "Setting up Python environment..."
cd backend
python3 -m venv .venv
source .venv/bin/activate
pip install -q --upgrade pip
pip install -q -r requirements.txt
cd ..
ok "Python dependencies installed (backend/.venv)"

# ── 6. Node dependencies ──────────────────────────────────────────────────────
echo ""
echo "Installing frontend dependencies..."
cd frontend && npm install --silent && cd ..
ok "Node dependencies installed"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════"
echo "  Setup complete. Next steps:"
echo "═══════════════════════════════════════"
echo ""
echo "  Pull Ollama models (if not done):"
echo "    ollama pull qwen2.5:14b"
echo "    ollama pull nomic-embed-text"
echo ""
echo "  Start backend (terminal 1):"
echo "    cd backend && source .venv/bin/activate && uvicorn main:app --reload --port 8000"
echo ""
echo "  Start frontend (terminal 2):"
echo "    cd frontend && npm run dev"
echo ""
echo "  Verify health:"
echo "    curl http://localhost:8000/api/health"
echo ""
echo "  Open app:      http://localhost:3000"
echo "  Open Langfuse: http://localhost:3001"
echo ""
echo "  One-time evaluator setup (after first backend start):"
echo "    1. Log into Langfuse → Settings → LLM Connections → Add"
echo "       Provider: OpenAI | Base URL: http://host.docker.internal:11434/v1"
echo "       API Key: ollama | Model: qwen2.5:14b"
echo "    2. bash backend/setup_langfuse_evals.sh"
echo ""
